"""Add last_login and is_admin to users

Revision ID: 013a575e133c
Revises: f161848c10fd
Create Date: 2026-03-04 15:00:53.478288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013a575e133c'
down_revision = 'f161848c10fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
