"""Initial Plant Chap models

Revision ID: 4791f4c08486
Revises: 
Create Date: 2026-03-01 14:06:57.032712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4791f4c08486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strain', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('grow_space', sa.String(length=100), nullable=True),
    sa.Column('date_planted', sa.DateTime(), nullable=True),
    sa.Column('date_flipped', sa.DateTime(), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crops_user_id'), ['user_id'], unique=False)

    op.create_table('amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amendments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amendments_crop_id'), ['crop_id'], unique=False)

    op.create_table('grow_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grow_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grow_log_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grow_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('plant_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ph_runoff', sa.Float(), nullable=True),
    sa.Column('ph_feed', sa.Float(), nullable=True),
    sa.Column('ec_ppm', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('light_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_parameters_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_parameters_timestamp'), ['timestamp'], unique=False)

    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(), nullable=True),
    sa.Column('next_due', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('specific_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_next_due'), ['next_due'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_next_due'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_crop_id'))

    op.drop_table('scheduled_tasks')
    with op.batch_alter_table('plant_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_parameters_timestamp'))
        batch_op.drop_index(batch_op.f('ix_plant_parameters_crop_id'))

    op.drop_table('plant_parameters')
    with op.batch_alter_table('grow_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grow_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_grow_log_crop_id'))

    op.drop_table('grow_log')
    with op.batch_alter_table('amendments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amendments_crop_id'))

    op.drop_table('amendments')
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crops_user_id'))

    op.drop_table('crops')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
