"""Add crop photo and strain info fields

Revision ID: c7eddcf8a56a
Revises: e1d47b740c22
Create Date: 2026-03-04 14:12:33.688900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7eddcf8a56a'
down_revision = 'e1d47b740c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('strain_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strain_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('strain_lineage', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('strain_breeder', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_column('strain_breeder')
        batch_op.drop_column('strain_lineage')
        batch_op.drop_column('strain_type')
        batch_op.drop_column('strain_description')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
