"""Add VPD, PPFD, water_mbars to PlantParameter

Revision ID: e1d47b740c22
Revises: 4791f4c08486
Create Date: 2026-03-01 14:20:16.495301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d47b740c22'
down_revision = '4791f4c08486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vpd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ppfd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_mbars', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_parameters', schema=None) as batch_op:
        batch_op.drop_column('water_mbars')
        batch_op.drop_column('ppfd')
        batch_op.drop_column('vpd')

    # ### end Alembic commands ###
