"""Add strain_lineage_tree field

Revision ID: f161848c10fd
Revises: c7eddcf8a56a
Create Date: 2026-03-04 14:53:22.708963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f161848c10fd'
down_revision = 'c7eddcf8a56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strain_lineage_tree', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_column('strain_lineage_tree')

    # ### end Alembic commands ###
